name: Build and deploy

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: build dist
        run: |
          ./dist.sh
          ls -la

      - name: create release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "adguardcert-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          prerelease: ${{ contains(github.ref, '-') }}

      - name: write PR url
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ github.event.pull_request.html_url }}" > pull_request_url.txt

      - name: upload artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: adguardcert module build
          path: |
            adguardcert-*.zip
            README.md
            pull_request_url.txt

      - name: update json
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
          git fetch origin
          ./update.sh
          git push origin master
          ls -la
